"""add uniqueness to item_name

Revision ID: 878798caa589
Revises: ac0138a21b68
Create Date: 2024-10-08 00:21:13.044026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878798caa589'
down_revision = 'ac0138a21b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['item_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
