"""update RestockOrder table name

Revision ID: ac0138a21b68
Revises: e524fb671412
Create Date: 2024-10-07 22:59:24.040264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0138a21b68'
down_revision = 'e524fb671412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restock_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=False),
    sa.Column('order_quantity', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_restock_orders_item_id_items')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_restock_orders_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_status', sa.VARCHAR(), nullable=False),
    sa.Column('order_quantity', sa.INTEGER(), nullable=False),
    sa.Column('order_date', sa.DATE(), nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='fk_orders_item_id_items'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='fk_orders_supplier_id_suppliers'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('restock_orders')
    # ### end Alembic commands ###
